### ISSUE TITLE
【语音服务api】如何在不通外网的机器使用代理访问语音服务 SingleCallByTtsWithOptions

### ISSUE THREAD

**Issue by kwenzh** [aliyun/alibabacloud-go-sdk#11]
访问这个方法： SingleCallByTtsWithOptions

本地开发、测试环境不通外网dyvmsapi.aliyuncs.com ，有一台A机器通外网，我搭了一个四层代理出去访问dyvmsapi.aliyuncs.com。
然后我指定endpoint为A机器的地址。

遇到的问题是：
1、需要在header里面指定：host：dyvmsapi.aliyuncs.com，但看了代码发起请求是去的header的host来作为domain请求的。
https://github.com/alibabacloud-go/tea/blob/master/tea/tea.go#L305
```
requestURL := ""
	request.Domain = request.Headers["host"]
	requestURL = fmt.Sprintf("%s://%s%s", StringValue(request.Protocol), StringValue(request.Domain), StringValue(request.Pathname))
	queryParams := request.Query
```

2 强制修改dyvmsapi.aliyuncs.com解析到A机器的ip，会遇到问题：StatusCode: 0
   Code: SignatureDoesNotMatch
   Message: code: 400, Specified signature does not match our calculation. server StringToSign

有什么好的方法在不通外网的机器 测试吗？

**Comment by TsinghuaDream** [comment]
有专门的代理配置参数的，不是改host
https://help.aliyun.com/zh/sdk/developer-reference/configure-a-proxy-2
