### ISSUE TITLE
go mod 依赖版本错误 导致编译失败 tea-utils

### ISSUE THREAD

**Issue by ThereWeGo** [aliyun/alibabacloud-go-sdk#48]
/data/go/pkg/mod/github.com/alibabacloud-go/ecs-20140526/v2@v2.1.3/client/client.go:66164:45: cannot use runtime (variable of type *"github.com/alibabacloud-go/tea-utils/service".RuntimeOptions) as type *"github.com/alibabacloud-go/tea-utils/v2/service".RuntimeOptions in argument to client.CallApi

go.mod
	github.com/alibabacloud-go/darabonba-openapi v0.2.0
	github.com/alibabacloud-go/ecs-20140526/v2 v2.1.3
	github.com/alibabacloud-go/tea v1.1.19

	github.com/alibabacloud-go/tea-utils v1.4.5 // indirect
	github.com/alibabacloud-go/tea-utils/v2 v2.0.0 // indirect

**Comment by tangqiu0205** [comment]
同样的问题。

**Comment by Yullin** [comment]
Same Problem:
```
main/main.go:31:48: cannot use config (variable of type *"github.com/alibabacloud-go/darabonba-openapi/v2/client".Config) as type *"github.com/alibabacloud-go/darabonba-openapi/client".Config in argument to waf_openapi20211001.NewClient
main/main.go:44:76: cannot use runtime (variable of type *"github.com/alibabacloud-go/tea-utils/v2/service".RuntimeOptions) as type *"github.com/alibabacloud-go/tea-utils/service".RuntimeOptions in argument to client.DescribeInstanceWithOptions
```

**Comment by TsinghuaDream** [comment]
fixed.
