### ISSUE TITLE
arms返回Prometheus告警信息绑定结构体失败

### ISSUE THREAD

**Issue by sihouzhao** [aliyun/alibabacloud-go-sdk#52]
Prometheus 返回的告警列表Annotations 是个map绑定结构体报错

![struct](https://user-images.githubusercontent.com/32085413/198557451-520df877-565c-4764-a6fd-0450bf37af3f.png)

// tea@v1.1.19
![tea](https://user-images.githubusercontent.com/32085413/198557498-019a8b3e-121f-4466-8907-cbd35f0a2e76.png)

client.ListAlertEventsResponseBodyPageBeanEvents.Annotations: fuzzyStringDecoder: not number or string or bool, error found in #10 byte of ...|otations":{"aliyun|..., bigger context ...|Name

**Comment by TsinghuaDream** [comment]
fixed.
