### ISSUE TITLE
dataworks的api创建自定义报警规则，报警方式不支持WebHook

### ISSUE THREAD

**Issue by ipeng666** [aliyun/alibabacloud-go-sdk#53]
api地址：https://next.api.aliyun.com/api/dataworks-public/2020-05-18/CreateRemind
入参：AlertMethods，枚举值只有 MAIL：邮件，SMS：短信，PHONE：电话三种，但是在网页端操作是支持WebHook的，可以配置WebHook地址，但是在api当中好像没有~

**Comment by TsinghuaDream** [comment]
fixed.

**Comment by ipeng666** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我最近正在忙碌中，无法亲自回复您的邮件。我会尽快给您回复。对此，感到很抱歉！
