### ISSUE TITLE
开发sdk的人太垃圾了吧

### ISSUE THREAD

**Issue by guomouren** [aliyun/alibabacloud-go-sdk#55]
如题，版本测试了吗？单元测试了吗？文档更新了吗？

**Comment by df1228** [comment]
而且很混乱 找个函数计算的go sdk，结果这个看起来也像，那个看起来也像。。。。

**Comment by TsinghuaDream** [comment]
各项问题都在解决中的：
文档问题，我们展开了文档抓虫任务。
测试问题，我们提升了测试的覆盖度要求。
至于找SDK的问题，可以通过门户https://api.aliyun.com/调试且获取安装命令，即不用再到Git。
