### ISSUE TITLE
alibabacloud-go / cdn-20180510 的master分支可以给个tag吗

### ISSUE THREAD

**Issue by beckliln** [aliyun/alibabacloud-go-sdk#56]
alibabacloud-go / cdn-20180510 的master分支可以给个tag吗，master分支与最新的2.0.6分支代码不一致

**Comment by TsinghuaDream** [comment]
可以通过门户查看最新版本https://api.aliyun.com/api-tools/sdk/dcdn?spm=api-workbench.Product%20Home%20Page.0.0.76e0e85ceg74zJ&version=2018-01-15&language=go-tea&tab=history-version
![image](https://github.com/aliyun/alibabacloud-go-sdk/assets/43798276/b0c74848-512c-45c5-8f21-cc7eb8d0141d)
