### ISSUE TITLE
facebody-20191230

### ISSUE THREAD

**Issue by joostshao** [aliyun/alibabacloud-go-sdk#6]
问题：panic: SDKError:
   Code: InvalidParameter.TooLarge
   Message: code: 400, ImageURL's size should be less than 3145728 request id: ED7CE726-9632-56FD-B937-D2FE86F6DD69
  
 为什么图片会有大小小于3MB的限制呢？你们有对应的图片转码服务吗？

**Comment by TsinghuaDream** [comment]
限制一般API文档有介绍的，关于图片缩放，可以看下这篇文档https://help.aliyun.com/zh/oss/user-guide/resize-images-4?spm=api-workbench.api_explorer.0.0.710170bcywxgdb
