### ISSUE TITLE
ListLoadBalancersResponseBodyLoadBalancersLoadBalancerBillingConfig missing fields

### ISSUE THREAD

**Issue by dongxuny** [aliyun/alibabacloud-go-sdk#62]
Package: github.com/alibabacloud-go/alb-20200616/v2
Struct: ListLoadBalancersResponseBodyLoadBalancersLoadBalancerBillingConfig

Newest response from aliyun CLI like bellow: 
{
	"LoadBalancers": [
		{
			"AccessLogConfig": {},
			"AddressAllocatedMode": "Fixed",
			"AddressIpVersion": "Ipv4",
			"AddressType": "Internet",
			"CreateTime": "2023-10-10T15:38:00Z",
			"DNSName": "alb-rd1hizzt6eyj1ejxvk.cn-hangzhou.alb.aliyuncs.com",
			"DeletionProtectionConfig": {
				"Enabled": false
			},
			"LoadBalancerBillingConfig": {
				"InternetBandwidth": 400,
				"InternetChargeType": "PayByTraffic",
				"PayType": "PostPay"
			},
			"LoadBalancerBussinessStatus": "Normal",
			"LoadBalancerEdition": "Basic",
			"LoadBalancerId": "alb-rd1hizzt6eyj1ejxvk",
			"LoadBalancerName": "alb-demo",
			"LoadBalancerStatus": "Active",
			"ModificationProtectionConfig": {},
			"ResourceGroupId": "rg-acfmwrne2i563aa",
			"VpcId": "vpc-bp1vi1sbq5ircuff032gn"
		}
	],
	"MaxResults": 20,
	"RequestId": "1D217B05-90E8-5D2B-B5E1-8255566C86B5",
	"TotalCount": 1
}

However, SDK missing InternetBandwidth & InternetChargeType in LoadBalancerBillingConfig

**Comment by TsinghuaDream** [comment]
The field list is mainly based on the document description. Please ignore the fields that are not described in the document.
InternetBandwidth & InternetChargeType is not in LoadBalancer API document.
