### ISSUE TITLE
ListObjectsV2 如果返回结果中只有1个文件ListObjectsV2Response反序列化时报错

### ISSUE THREAD

**Issue by wdyangkun** [aliyun/alibabacloud-go-sdk#64]
如题，报错如下

client.ListObjectsV2Response.Body: client.ListObjectsV2ResponseBody.Contents: []*client.ObjectSummary: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ontents":{"ETag":"\"|..., bigger context ...|{"body":{"Contents":{"ETag":"\"4C7F0BB373E72250991C3A913117B1B7\"","Key|...

**Comment by TsinghuaDream** [comment]
OSS的golangSDK请先使用这个。https://help.aliyun.com/zh/oss/developer-reference/go/?spm=a2c4g.11174283.0.0.2aa37368hEe9p5
