### ISSUE TITLE
github ons-20190214 v1.0.2版本的包和 OpenApi在线调试平台下载的完整工程包有差异，github包没有mq消息体参数，希望能更新一下

### ISSUE THREAD

**Issue by Nevermore-dh** [aliyun/alibabacloud-go-sdk#8]
OpenApi地址：https://next.api.aliyun.com/api/Ons/2019-02-14/OnsMessageGetByMsgId?tab=DEMO&lang=GO
调试平台的包：<img width="1126" alt="image" src="https://user-images.githubusercontent.com/19945930/156705987-a45613d7-ea3f-4b04-a3e5-b75a7960002d.png">
github ons-20190214 v1.0.2 的包：<img width="1100" alt="image" src="https://user-images.githubusercontent.com/19945930/156706124-06ca8816-0dce-4587-a36a-2ff98c45389b.png">

**Comment by TsinghuaDream** [comment]
要安装V2的
go get github.com/alibabacloud-go/ons-20190214/v2
