### ISSUE TITLE
Lack of licenses on SDKs

### ISSUE THREAD

**Issue by Phuurl** [aliyun/alibabacloud-go-sdk#9]
None of the Go SDKs appear to have a license attached to them (at least not in the standard way - with a `LICENSE.md` or similar file in the repos).

This prevents both the standard Go tools from rendering the documentation (for example see https://pkg.go.dev/github.com/alibabacloud-go/ecs-20140526@v1.0.5/client for the error displayed for the ECS client), and organisations from using it as it is not known what license the code is released under.

Please specify the license that these SDKs are released with in a manner compliant with [Go's standards](https://pkg.go.dev/license-policy). Thanks 🙂

**Comment by TsinghuaDream** [comment]
fixed.
